In [1]:
import numpy as np
import pandas as pd

In [34]:
# Dummy dataset
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [35]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [36]:
def initialize_parameters(layer_dims):
  
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)         

    for l in range(1, L):

        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

    return parameters
        

In [37]:
initilize_parameters([2,2,1])

{'W1': array([[1., 1.],
        [1., 1.]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[1.],
        [1.]]),
 'B2': array([[0.]])}

In [38]:
def linear_forward(A_prev, W, b):
  
    Z = np.dot(W.T, A_prev) + b

    return Z

In [39]:
# Forward Prop
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2                  # number of layers in the neural network

    for l in range(1, L+1):
        A_prev = A 
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        #print("A"+str(l-1)+": ", A_prev)
        #print("W"+str(l)+": ", Wl)
        #print("b"+str(l)+": ", bl)
        #print("--"*20)

        A = linear_forward(A_prev, Wl, bl)
        #print("A"+str(l)+": ", A)
        #print("**"*20)

    return A,A_prev

In [40]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [41]:
print("y_hat", y_hat, " A1", A1, " parameter", parameters)

y_hat [[0.32]]  A1 [[1.6]
 [1.6]]  parameter {'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


In [44]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [45]:
# Trainning with Epoch
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

    Loss = []

    for j in range(df.shape[0]):

        X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
        y = df[['lpa']].values[j][0]

        # Parameter initialization


        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)

        Loss.append((y-y_hat)**2)

    print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [46]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [47]:
model = Sequential()

model.add(Dense(2, activation="linear", input_dim = 2))
model.add(Dense(1, activation="linear"))

In [48]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [52]:
model.get_weights()

[array([[-0.1132127, -0.1694268],
        [ 0.9448911,  0.9078361]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.6820665],
        [ 0.8958701]], dtype=float32),
 array([0.], dtype=float32)]

In [68]:
new_weight = [np.array([[1,1],[ 1, 1]], dtype=np.float32),
             np.array([0, 0], dtype=np.float32),
             np.array([[1],
                    [1]], dtype=np.float32),
             np.array([0], dtype=np.float32)]

In [69]:
new_weight

[array([[1., 1.],
        [1., 1.]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.],
        [1.]], dtype=float32),
 array([0.], dtype=float32)]

In [70]:
model.set_weights(new_weight)

TypeError: 'list' object is not callable

In [71]:
model.get_weights()

[array([[-0.1132127, -0.1694268],
        [ 0.9448911,  0.9078361]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.6820665],
        [ 0.8958701]], dtype=float32),
 array([0.], dtype=float32)]